Barbies/barbieproject/barbieapp/urls.py
from django.urls import path
from . import views
app_name='barbieapp'
urlpatterns = [
    path('',views.copying,name='copying'),
    path('cutie/<int:barb_id>/',views.detail,name='detail'),
    path('adding/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('deleted/<int:id>/',views.deleted,name='deleted')
]

Barbies/barbieproject/barbieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('barbieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Barbies/barbieproject/barbieapp/models.py
from django.db import models

# Create your models here.
class cutie(models.Model):
    name=models.CharField(max_length=150)
    price=models.IntegerField()
    style=models.TextField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

Barbies/barbieproject/barbieapp/forms.py
from django import forms
from .models import cutie
class barbieform(forms.ModelForm):
    class Meta:
        model = cutie
        fields = ['name','price','style','img']

Barbies/barbieproject/barbieapp/views.py
#
from django.shortcuts import render, redirect
from . models import cutie
from .forms import barbieform
# Create your views here.
def copying(request):
    beauty=cutie.objects.all()
    context={
        'smile_list':beauty
    }
    return render(request,'index.html',context)
def detail(request, barb_id,):
    beauty=cutie.objects.get(id=barb_id)
    return render(request,'detail.html',{'ken':beauty})

def add(request):
    if request.method=="POST":
        name = request.POST.get('name')
        price = request.POST.get('price')
        style = request.POST.get('style')
        img = request.FILES['img']
        barbie = cutie(name=name,price=price,style=style,img=img)
        barbie.save()
        return redirect('/')
    return render(request,'adding.html')

def update(request,id):
    res=cutie.objects.get(id=id)
    form=barbieform(request.POST or None,request.FILES,instance=res)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html',{'form':form,'res':res })
def edit(request,id):
    res=cutie.objects.get(id=id)
    form=barbieform(request.POST or None,request.FILES,instance=res)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'res':res})

def deleted(request,id):
    if request.method=="POST":
        dele = cutie.objects.get(id=id)
        dele.delete()
        return redirect('/')
    return render(request,'deleted.html')

Barbies/barbieproject/templates/adding.html
{% extends 'base.html' %}
{% block body %}

<form  method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="text" name="name" placeholder="Enter your movie name"><br>
      <input type="text" name="price" placeholder="Enter movie price"><br>
      <input type="text" name="style" placeholder="Enter movie genre"><br>
      <input type="file" name="img"><br>
      <input type="submit" >
</form>
{% endblock %}

Barbies/barbieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Website</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'barbieapp:copying' %}">
        MOVIE
    </a>
  </div>
</nav>
<form method="POST" enctype="multipart/form-data">
<!--    {% csrf_token %}-->
<!--    {{form.as_p}}-->
     

</form>
{% block body %}
{% endblock %}
</body>
</html>

Barbies/barbieproject/templates/deleted.html
<form method="POST">

  {% csrf_token %}
  <input type="submit">
</form>

Barbies/barbieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
 <div class="row">
  <div class="col-md-6">
<!--   <img src="{{ken.img.url}}" width='300' height='300'>-->
  </div>
<div class="col-md-6">
<!--     <h4>{{ken.name}}</h4>-->
<!--     <h5>{{ken.style}}</h5>-->
<!--     <h6>{{ken.price}}</h6><br>-->
     <a class="btn btn-warning" href="{% url 'barbieapp:update' ken.id %}">Add</a>
     <a class="btn btn-danger" href="{% url 'barbieapp:deleted' ken.id %}">Delete</a>
 </div>
  </div>
</div>
{% endblock %}

Barbies/barbieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <h1>edit</h1>
    <input type="submit">
</form>

Barbies/barbieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}



<div class="container">
    <div class="row">
        {% for i in smile_list %}
        <div class="col-md-3">
            <div class="card">
                <img src="{{i.img.url}}" class="card-img-top" alt="" height="250px">
                <div class="card-body">
                   <h4 class="card-title">{{i.name}}</h4>
                   <p class="card-text">{{i.style}}</p>
                   <h5 class ="card-price">{{i.price}}</h5>
                   <a href="{% url 'barbieapp:update' i.id %}" class="btn btn-primary">Update</a>
                   <a href="{% url 'barbieapp:deleted' i.id %}" class="btn btn-primary">Delete</a>
                </div>
             </div>
        </div>
   
        {% endfor %}
    </div>
    <a href="{% url 'barbieapp:add'%}" class="btn btn-primary">Add Movie</a>
</div>







{% endblock %}

Barbies/barbieproject/templates/update.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="text" name="name" value={{res.name}}><br>
      <input type="text" name="price" value={{res.style}}><br>
      <input type="text" name="style" value={{res.price}}><br>
      <input type="file" name="img" value="{{res.img.url}}"><br>
      <input type="submit">
</form>
{% endblock %}